# Generated by Django 5.2.8 on 2025-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['platform']},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('reddit', 'Reddit'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('medium', 'Medium'), ('devto', 'Dev.to'), ('codepen', 'CodePen'), ('stackoverflow', 'Stack Overflow'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
