# Generated by Django 5.2.8 on 2025-12-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_socialmedia_options_socialmedia_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF recommended)', null=True, upload_to='cv/'),
        ),
    ]
