# Generated by Django 5.2.8 on 2025-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_aboutme_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='clients',
            field=models.IntegerField(blank=True, default=0, help_text='Number of clients (leave blank to show N/A)', null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='years_of_experience',
            field=models.IntegerField(default=0, help_text='Years of professional experience'),
        ),
    ]
