# Generated by Django 5.2.8 on 2025-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aboutme_clients_aboutme_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload a custom logo image (optional). If not provided, a text logo will be used.', null=True, upload_to='logo/'),
        ),
    ]
