# Generated by Django 5.2.8 on 2025-12-02 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_aboutme_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='logo_image',
            field=models.FileField(blank=True, help_text='Upload a custom logo image (PNG, JPG, SVG, etc.). If not provided, a text logo will be used.', null=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'svgz'])]),
        ),
    ]
