# Generated by Django 5.2.8 on 2025-12-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_contactinfo_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin/system portfolio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin/system portfolio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin/system portfolio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin/system portfolio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin/system portfolio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin/system portfolio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_slug', models.SlugField(blank=True, help_text='Unique URL slug for portfolio (e.g., /username)', max_length=100, null=True, unique=True)),
                ('portfolio_published', models.BooleanField(default=False, help_text='Whether the portfolio is publicly accessible')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval required before user can access dashboard')),
                ('email_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('email_verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Portfolio banner/header image', null=True, upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
