# Generated by Django 5.2.8 on 2025-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_contactmessage_user_alter_contactmessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_otp_expires',
            field=models.DateTimeField(blank=True, help_text='OTP expiration time', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='OTP code for email verification', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin approval required before user can access dashboard'),
        ),
    ]
